### ISSUE TITLE
NiceHashMinerLegacy.exe crashing no errors 1.9.0.1

### ISSUE THREAD

**Issue by glassd** [nicehash/NiceHashMiner#1172]
Nicehash Miner application itself will crash with no warning or reason. The miners currently active will stay running and complete their current tasks and show on the status page. This is a fresh install and benchmark of 1.9.0.1 so all new configs. Nothing has been brought over from an earlier version. Here is the tail end of the log with the only error I can see in it.

Also of note.... Who is Dillon?

```
[2018-05-04 17:32:22] [INFO] [CPUDIAG] System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter.Initialize()
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NiceHashMiner.Devices.CpuComputeDevice.get_Load() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDevice\CpuComputeDevice.cs:line 17
[2018-05-04 17:32:22] [INFO] [SOCKET] Sending data: {"method":"devices.status","devices":[[0,"Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz",2,-1,-1,-1],[1,"MSI GeForce GTX 1060 6GB",5,99,59,1555],[2,"MSI GeForce GTX 1060 6GB",5,99,56,1477],[3,"MSI GeForce GTX 1060 6GB",5,100,55,1473],[4,"MSI GeForce GTX 1060 6GB",5,100,59,1553],[5,"MSI GeForce GTX 1060 6GB",5,100,59,1560],[6,"Radeon RX 580 Series",7,100,78,1475],[7,"Radeon RX 580 Series",7,100,78,1475],[8,"Radeon RX 580 Series",7,100,78,1475],[9,"Radeon RX 580 Series",7,100,78,1475],[10,"Radeon RX 580 Series",7,100,78,1475],[11,"Radeon RX 580 Series",7,100,78,1475],[12,"Radeon RX 580 Series",7,100,78,1475],[13,"Radeon RX 580 Series",7,100,78,1475]]}
```

**Comment by Geesu** [comment]
Same. Mine crashes the second benchmarking starts.

**Comment by inventorAdam5** [comment]
1.9.0.0 and 1.9.0.3 same issue with me. been able to work around it using a batch file and an auto clicker to restart it and bypass the annoying 'check your connection' error message. but its still a pain in the rear.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
