### ISSUE TITLE
nhml 1.9.1.0 has a repeating error that causes a bsod

### ISSUE THREAD

**Issue by dasGiggler** [nicehash/NiceHashMiner#1329]
my gear:
asrock x399 tiachi motherboard 
1950x gpu
16gb ram
500gb ssd
3 1080ti

I am using NHML v1.9.1.0 on windows 10 pro.
I keep getting this repeating in my debug console when i run nhlm. 

[20:59:36] [CPUDIAG] System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter.Initialize()
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NiceHashMiner.Devices.CpuComputeDevice.get_Load() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDevice\CpuComputeDevice.cs:line 18
 
This begins at startup. It causes the comp to slow down extremely.  Sometimes when I start mining it goes away, but eventually causes a bsod.  When I try to view the dump files with whocrashed it now causes whocrashed to crash.  I have deleted nhml and reinstalled it and the same thing happens.  I also tried turning off 3rd party apps and enlargement pill.  I do not have a user file or directory called "Dillon" on my comp.  Any help would be greatly appreciated.  Thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
