### ISSUE TITLE
WebSocket.connect TLS handshake error

### ISSUE THREAD

**Issue by JohnFoe** [nicehash/NiceHashMiner#1657]
NHML 1.9.1.7 (and other older versions tried)

Opening it gets message:

---------------------------
Check internet connection
---------------------------
NiceHash Miner Legacy requires internet connection to run. Please ensure that you are connected to the internet before running NiceHash Miner Legacy. Would you like to continue?
---------------------------
Yes   No   
---------------------------

Answering Yes continues and eventually the status says "Error" when I try to start it.

[2019-07-09 13:04:03] [INFO] [MinerPluginsManager] Finished initialization of miners.
[2019-07-09 13:04:05] [INFO] [SOCKET] 07/09/2019 13:04:05|Warn |Logger.set_Output|The current output action has been changed.
[2019-07-09 13:04:05] [INFO] [SOCKET] Connecting
[2019-07-09 13:04:05] [INFO] [SOCKET] 07/09/2019 13:04:05|Fatal|WebSocket.connect|An error has occurred during a TLS handshake.
[2019-07-09 13:04:05] [INFO] [SOCKET] 07/09/2019 13:04:05|Debug|WebSocket.connect|WebSocketSharp.WebSocketException: An error has occurred during a TLS handshake. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
                             at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
                             at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
                             at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
                             at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
                             at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
                             at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
                             at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
                             at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
                             at WebSocketSharp.WebSocket.setClientStream()
                             --- End of inner exception stack trace ---
                             at WebSocketSharp.WebSocket.setClientStream()
                             at WebSocketSharp.WebSocket.doHandshake()
                             at WebSocketSharp.WebSocket.connect()
[2019-07-09 13:04:05] [INFO] [SOCKET] 07/09/2019 13:04:05|Debug|WebSocket.closeHandshake|Was clean?: False
                            sent: False
                            received: False
[2019-07-09 13:04:05] [INFO] [NiceHashSocket] Connection closed code 1015: An exception has occurred while attempting to connect.
[2019-07-09 13:04:05] [INFO] [SOCKET] Attempting reconnect in 0 seconds
[2019-07-09 13:04:05] [INFO] [SOCKET] 07/09/2019 13:04:05|Fatal|WebSocket.connect|An error has occurred during a TLS handshake.

[log.txt](https://github.com/nicehash/NiceHashMiner/files/3374082/log.txt)

**Comment by grichter** [comment]
At a guess you're missing a required runtime. Make sure you have the required vc runtime and net framework versions.
