### ISSUE TITLE
Nicehash Miner 1.9.2.10 System.Exception: NVML power get failed with status: GPUIsLost    at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.get_PowerUsage() in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 175

### ISSUE THREAD

**Issue by huanghongyie** [nicehash/NiceHashMiner#1695]
i check my Nicehash log and found these errors, What does it mean?
Is it hardware failure? My GPU GTX1080ti can mine Daggerhashimoto without issue. 
My hardware:
- CPU: Core i5 4460
- RAM: 8GB
- GPU: GTX 1080ti, GTX 1070
- Nicehash Legacy 1.9.2.10
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3429221/log.txt)

[2019-07-25 07:05:13] [ERROR] [NVML] System.Exception: NVML power get failed with status: GPUIsLost
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.get_PowerUsage() in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 175
[2019-07-25 07:05:13] [ERROR] [NVML] System.Exception: NVML get load failed with code: GPUIsLost
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.get_Load() in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 109
[2019-07-25 07:05:13] [ERROR] [NVML] System.Exception: NVML get temp failed with code: GPUIsLost
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.get_Temp() in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 134
[2019-07-25 07:05:13] [ERROR] [NVAPI] Tach get failed with status: NVIDIA_DEVICE_NOT_FOUND

**Comment by luc1an24** [comment]
Hi @huanghongyie 
Thank you for reaching out and sorry for slow reply.
This sould be fixed in the new [1.9.2.11](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.2.11/nhm_windows_1.9.2.11.zip) version.
The issue here is with the crashed driver and the new version tries to restart it every time it detects failed driver.
If the issue persist please reopen the issue.

**Comment by CsakiTheOne** [comment]
I have this issue on NiceHash version 3.0.5.1. I have an Nvidia GTX 1050.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/5544714/log.txt)

**Comment by EddWills95** [comment]
I also have the same issue with an Nvidia GTX 1050

**Comment by paulogaspar** [comment]
I have a similar issue with Nvidia GTX 1050. Keeps failing and restarting. Log error:

```
[2021-03-17 19:11:17] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-1cd354fe-1c3f-8483-9882-62ea289a9414)-busid(1)] NHM.DeviceMonitoring.NVIDIA.NvmlException: NVML failed with code NotSupported. For 'nvmlDeviceGetFanSpeed'
   em NHM.DeviceMonitoring.DeviceMonitorNVIDIA.<NHM.DeviceMonitoring.IGetFanSpeedPercentage.GetFanSpeedPercentage>b__17_0()
   em NHM.DeviceMonitoring.DeviceMonitorNVIDIA.ExecNvmlProcedure[T](T failReturn, String tag, Func`1 nvmlExecFun)
```

**Comment by andrewijaya98** [comment]
[2021-06-15 18:26:14] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-757dc3a4-8bbe-f9d0-4ba3-345053cab6fe)-busid(3)] NHM.DeviceMonitoring.NVIDIA.NvmlException: NVML failed with code Unknown. For 'nvmlDeviceGetFanSpeed'
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.<NHM.DeviceMonitoring.IGetFanSpeedPercentage.GetFanSpeedPercentage>b__17_0()
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.ExecNvmlProcedure[T](T failReturn, String tag, Func`1 nvmlExecFun) 



i got this error too using 3060 on octopus
