### ISSUE TITLE
Strange exception during profitability check.

### ISSUE THREAD

**Issue by Mystere** [nicehash/NiceHashMiner#179]
I have the debug console open, and i see this, it happens every time a profitability check is made.  It's been there for several versions (since the switch to websockets i believe)

[CPUDIAG] System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter.Initialize()
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NiceHashMiner.Devices.CPUComputeDevice.get_Load() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDevice\CPUComputeDevice.cs:line 18

Everything seems to work ok, i just don't like exceptions in my logs :)

Can you fix?

**Comment by DillonN** [comment]
Hello @Mystere, could you try the steps listed in the last section on [this Wiki page](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Rig-Stats-Monitoring)

**Comment by Mystere** [comment]
that fixed it.  sorry i didn't notice the wiki info

**Comment by DillonN** [comment]
No worries, I'll close this now
