### ISSUE TITLE
NHM 1.9.2.15 hangs sometimes

### ISSUE THREAD

**Issue by konstantinpavlow** [nicehash/NiceHashMiner#1831]
Hello, 
from time to time 1.9.2.15 mining hangs with the error below, please help to identify the root cause

E.g. (hanged around 2019-10-06 00:41, full log is also 
[hang.zip](https://github.com/nicehash/NiceHashMiner/files/3694069/hang.zip)
attached):

[2019-10-06 00:41:28] [INFO] [MiningManager] Mine always regardless of profit
[2019-10-06 00:41:28] [INFO] [MiningManager] PrevStateProfit 0,000344092377063599, CurrentProfit 0,000344631105313632
[2019-10-06 00:41:28] [INFO] [MiningManager] Will NOT switch profit diff is 0,00156565005778702, current threshold 0,05
[2019-10-06 00:41:31] [INFO] [CUDADetector] TryQueryCUDADevicesAsync END cuda -n -nvmlFallback
[2019-10-06 00:41:40] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-ce74c2af-7963-fc51-eb92-1bcbda04987d)-busid(5)] NHM.DeviceMonitoring.NVIDIA.NvmlException: NVML failed with code GPUIsLost. For 'nvmlDeviceGetUtilizationRates'
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.<get_Load>b__14_0() in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 102
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.ExecNvmlProcedure[T](T failReturn, String tag, Func`1 nvmlExecFun) in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 207
[2019-10-06 00:41:40] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-ce74c2af-7963-fc51-eb92-1bcbda04987d)-busid(5)] NHM.DeviceMonitoring.NVIDIA.NvmlException: NVML failed with code GPUIsLost. For 'nvmlDeviceGetTemperature'
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.<get_Temp>b__16_0() in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 120
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.ExecNvmlProcedure[T](T failReturn, String tag, Func`1 nvmlExecFun) in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 207
[2019-10-06 00:41:40] [ERROR] [NVAPI] Tach get failed with status: NVIDIA_DEVICE_NOT_FOUND
[2019-10-06 00:41:40] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-ce74c2af-7963-fc51-eb92-1bcbda04987d)-busid(5)] NHM.DeviceMonitoring.NVIDIA.NvmlException: NVML failed with code GPUIsLost. For 'nvmlDeviceGetPowerUsage'
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.<get_PowerUsage>b__20_0() in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 182
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.ExecNvmlProcedure[T](T failReturn, String tag, Func`1 nvmlExecFun) in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 207
[2019-10-06 00:41:41] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-24621fe6-d13a-1900-436b-9b2ff3743965)-busid(1)] NHM.DeviceMonitoring.NVIDIA.NvmlException: NVML failed with code Unknown. For 'nvmlDeviceGetUtilizationRates'
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.<get_Load>b__14_0() in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 102
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.ExecNvmlProcedure[T](T failReturn, String tag, Func`1 nvmlExecFun) in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 207
[2019-10-06 00:41:41] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-24621fe6-d13a-1900-436b-9b2ff3743965)-busid(1)] NHM.DeviceMonitoring.NVIDIA.NvmlException: NVML failed with code Unknown. For 'nvmlDeviceGetTemperature'
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.<get_Temp>b__16_0() in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 120
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.ExecNvmlProcedure[T](T failReturn, String tag, Func`1 nvmlExecFun) in D:\Programming\NiceHashMiner\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 207
[2019-10-06 00:41:49] [INFO] [SOCKET] Received: {"method":"sma","data":[[44,"9602.482889"],[46,"0.002918887883"],[7,"3.77813586e-06"],[8,"0.01283691219"],[21,"9.399993816e-09"],[29,"0.0001051199948"],[38,"9204.812553"],[23,"7.35512201e-07"],[33,"0.0009410770399"],[40,"0.0007014561695"],[45,"1623.299491"],[5,"9.000056872e-07"],[36,"763.0715772"],[22,"0.4593814947"],[37,"100.0001966"],[24,"5.622246775"],[20,"0.001519673744"],[34,"3.393665876"],[14,"7.632416484e-05"],[30,"0.9607236794"],[28,"1.150634839e-07"],[31,"9.999997251"],[43,"9170.049132"],[32,"0.0007078688974"],[42,"33.68042685"],[39,"63952.3837"]],"stable":"[44,8,38,40,45,36,37,24,20,14,30,43,39]"}
[2019-10-06 00:41:49] [INFO] [NHSMAData] Updating stable algorithms
	None changed

[2019-10-06 00:41:50] [INFO] [SOCKET] SendMinerStatus Tick 'miner.status'
[2019-10-06 00:41:50] [INFO] [DeviceMonitorNVIDIA-uuid(GPU-24621fe6-d13a-1900-436b-9b2ff3743965)-busid(1)] Load Will call NVML restart
[2019-10-06 00:41:51] [INFO] [NvidiaMonitorManager] Attempting to restart NVML
[2019-10-06 00:41:56] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-5e101fbb-0d63-3de0-728f-c7ea0aaf95da)-busid(2)] Skipping Load NVML IsRestarting
[2019-10-06 00:41:56] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-5e101fbb-0d63-3de0-728f-c7ea0aaf95da)-busid(2)] Skipping Temp NVML IsRestarting
[2019-10-06 00:41:56] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-2bc6d1a0-afeb-5bdb-b7d4-b93ec3eb2434)-busid(3)] Skipping Load NVML IsRestarting
[2019-10-06 00:41:56] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-2bc6d1a0-afeb-5bdb-b7d4-b93ec3eb2434)-busid(3)] Skipping Temp NVML IsRestarting
[2019-10-06 00:41:56] [ERROR] [DeviceMonitorNVIDIA-uuid(GPU-9e622580-4b66-9ffd-ff8b-4fe506a39e11)-busid(4)] Skipping Load NVML IsRestarting
[hangs.log](https://github.com/nicehash/NiceHashMiner/files/3694065/hangs.log)

**Comment by SomethingGettingWrong** [comment]
mines not hanging but my mouse freezes and windows dragging does as well . Acts like a cpu at 100 percent with no memmory left or something.  it does this on a fresh install. If i close nicehash computer is fine. Everything works but just seems.. well buggy.
