### ISSUE TITLE
Missing File and No Gminer

### ISSUE THREAD

**Issue by Joshwaa2010** [nicehash/NiceHashMiner#2068]
I have do not have Defender running or any anti-virus/anti-malware and keep getting the error of miners missing for Gminer 9.0+.

Also looking through the logs I see that the program is looking for something that does not exist on my system.  This happens frequently.  It is looking for C:\Programming\nicehash\NiceHashMiner\src\Miners\MinerPluginToolkitV1\MinerBase.cs:line 311

LOG-------------------------------------------------------------------------------------

[2020-05-13 07:57:42] [INFO] [1b7019d0-7237-11e9-b20c-f9f12eb6d835-MINER_ID(0)-DEVICE_IDs(1)] NEW MINER CREATED
[2020-05-13 07:57:42] [INFO] [1b7019d0-7237-11e9-b20c-f9f12eb6d835-MINER_ID(0)-DEVICE_IDs(1)] Starting miner watchdog task
[2020-05-13 07:57:43] [INFO] [Miner1-1b7019d0-7237-11e9-b20c-f9f12eb6d835-algo(GrinCuckatoo32)-devs(NVIDIA:1)] Starting miner binPath='C:\Users\Josh\AppData\Local\Programs\NiceHash Miner\miner_plugins\1b7019d0-7237-11e9-b20c-f9f12eb6d835\bins\10.0\miner.exe'
[2020-05-13 07:57:43] [INFO] [Miner1-1b7019d0-7237-11e9-b20c-f9f12eb6d835-algo(GrinCuckatoo32)-devs(NVIDIA:1)] Starting miner binCwd='C:\Users\Josh\AppData\Local\Programs\NiceHash Miner\miner_plugins\1b7019d0-7237-11e9-b20c-f9f12eb6d835\bins\10.0'
[2020-05-13 07:57:43] [INFO] [Miner1-1b7019d0-7237-11e9-b20c-f9f12eb6d835-algo(GrinCuckatoo32)-devs(NVIDIA:1)] Starting miner commandLine='-a cuckatoo32 --proto stratum --server grincuckatoo32.usa.nicehash.com:3383 -u XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -cBQ -d 1 -w 0 --api 4002 '
[2020-05-13 07:57:43] [INFO] [Miner1-1b7019d0-7237-11e9-b20c-f9f12eb6d835-algo(GrinCuckatoo32)-devs(NVIDIA:1)] Starting miner environmentVariables='<null>'
[2020-05-13 07:57:43] [ERROR] [Miner1-1b7019d0-7237-11e9-b20c-f9f12eb6d835-algo(GrinCuckatoo32)-devs(NVIDIA:1)] Error occured in StartMining : The system cannot find the file specified
[2020-05-13 07:57:43] [INFO] [f1945a30-7237-11e9-b20c-f9f12eb6d835-MINER_ID(0)-DEVICE_IDs(0)] NEW MINER CREATED
[2020-05-13 07:57:43] [INFO] [f1945a30-7237-11e9-b20c-f9f12eb6d835-MINER_ID(0)-DEVICE_IDs(0)] Starting miner watchdog task
[2020-05-13 07:57:43] [ERROR] [1b7019d0-7237-11e9-b20c-f9f12eb6d835-MINER_ID(0)-DEVICE_IDs(1)] StartAsync result: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at MinerPluginToolkitV1.MinerBase.<>c__DisplayClass68_0.<StartMiningTask>b__0() in C:\Programming\nicehash\NiceHashMiner\src\Miners\MinerPluginToolkitV1\MinerBase.cs:line 311

**Comment by Joshwaa2010** [comment]
I fixed the Gminer issue.  Found another post that had the info.

**Comment by luc1an24** [comment]
Hi @Joshwaa2010 
Good to hear that
What was the problem in your case?

**Comment by luc1an24** [comment]
Inactive thread.
Closing

**Comment by endomorphine** [comment]
> I fixed the Gminer issue. Found another post that had the info.

can you provide link to help the others who struggle with the same problem?

**Comment by endomorphine** [comment]
> I fixed the Gminer issue. Found another post that had the info.

@Joshwaa2010  can you provide link to help the others who struggle with the same problem?
