### ISSUE TITLE
1.8.1.1 bug when detecting single R2 290x ASUS card

### ISSUE THREAD

**Issue by anovickis** [nicehash/NiceHashMiner#238]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at NiceHashMiner.Devices.ComputeDeviceManager.Query.AMD.QueryAMD() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDeviceManager.cs:line 623
   at NiceHashMiner.Devices.ComputeDeviceManager.Query.QueryDevices(IMessageNotifier messageNotifier) in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDeviceManager.cs:line 167
   at NiceHashMiner.Form_Main.StartupTimer_Tick(Object sender, EventArgs e) in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Forms\Form_Main.cs:line 233
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NiceHashMinerLegacy
    Assembly Version: 1.8.1.1
    Win32 Version: 1.8.1.1
    CodeBase: file:///C:/Users/Alex%20P.%20Novickis.QCE3X/Desktop/miner/NiceHashMinerLegacy.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///C:/Users/Alex%20P.%20Novickis.QCE3X/Desktop/miner/Newtonsoft.Json.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Users/Alex%20P.%20Novickis.QCE3X/Desktop/miner/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2549.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MessageBoxManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Alex%20P.%20Novickis.QCE3X/Desktop/miner/MessageBoxManager.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

c:\xyz\Desktop\miner>AMDOpenCLDeviceDetection.exe
[{"PlatformName": "AMD Accelerated Parallel Processing","PlatformNum": 0,"Device
s" : [{"DeviceID" : 0,"AMD_BUS_ID" : 101,"_CL_DEVICE_NAME" : "Hawaii","_CL_DEVIC
E_TYPE" : "GPU","_CL_DEVICE_GLOBAL_MEM_SIZE" : 4294967296,"_CL_DEVICE_VENDOR" :
"Advanced Micro Devices, Inc.","_CL_DEVICE_VERSION" : "OpenCL 2.0 AMD-APP (2442.
8)","_CL_DRIVER_VERSION" : "2442.8"}]}]

retried installing drivers, 
fresh system image

Looking for my vs disk ... so I can see variables at runtime
hopefully I can build it

**Comment by anovickis** [comment]
here's "debug_all_out_amd.txt"
[
	{
		"PlatformName": "AMD Accelerated Parallel Processing",
		"PlatformNum": 0,
		"Devices" : [
			{
				"DeviceID" : 0,
				"AMD_BUS_ID" : 101,
				"_CL_DEVICE_NAME" : "Hawaii",
				"_CL_DEVICE_TYPE" : "GPU",
				"_CL_DEVICE_GLOBAL_MEM_SIZE" : 4294967296,
				"_CL_DEVICE_VENDOR" : "Advanced Micro Devices, Inc.",
				"_CL_DEVICE_VERSION" : "OpenCL 2.0 AMD-APP (2442.8)",
				"_CL_DRIVER_VERSION" : "2442.8"
			}
		]
	}
]
[04:12:56] CL Platform vendor: Advanced Micro Devices, Inc.                    
[04:12:56] CL Platform name: AMD Accelerated Parallel Processing                    
[04:12:56] CL Platform version: OpenCL 2.0 AMD-APP (2442.8)                    
[04:12:56] Platform devices: 1                    
[04:12:56] 	0	Hawaii                    
[04:12:56] Number of ADL devices: 1                    
[04:12:56] ATI ADL Overdrive5 API found.                    
[04:12:56] ATI ADL Overdrive6 API found.                    
[04:12:56] Found 6 logical ADL adapters                    
[04:12:56] ADL index 0, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:56] GPU 0 assigned: iAdapterIndex:0 iPresent:1 strUDID:PCI_VEN_1002&DEV_67B0&SUBSYS_046C1043&REV_00_4&30C250C0&0&0000A iBusNumber:101 iDeviceNumber:0 iFunctionNumber:0 iVendorID:1002 name:AMD Radeon R9 200 Series                    
[04:12:56] ADL index 1, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:56] ADL index 2, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:56] ADL index 3, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:56] ADL index 4, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:56] ADL index 5, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:56] GPU 0 AMD Radeon R9 200 Series hardware monitoring enabled                    
[04:12:56] ADL GPU 0 is Adapter index 0 and maps to adapter id 877961856                    
[04:12:56] GPU 0 BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:56] Failed to ADL_Overdrive5_ODPerformanceLevels_Get                    
[04:12:56] 1 GPU devices max detected                    
[04:12:56] Specified platform that does not exist                    
[04:12:56] clDevicesNum returned error, no GPUs usable                    
[04:12:56] 0 GPU devices max detected                    
[04:12:57] Specified platform that does not exist                    
[04:12:57] clDevicesNum returned error, no GPUs usable                    
[04:12:57] 0 GPU devices max detected                    
[04:12:57] CL Platform vendor: Advanced Micro Devices, Inc.                    
[04:12:57] CL Platform name: AMD Accelerated Parallel Processing                    
[04:12:57] CL Platform version: OpenCL 2.0 AMD-APP (2442.8)                    
[04:12:57] Platform devices: 1                    
[04:12:57] 	0	Hawaii                    
[04:12:57] Number of ADL devices: 1                    
[04:12:57] ATI ADL Overdrive5 API found.                    
[04:12:57] ATI ADL Overdrive6 API found.                    
[04:12:57] Found 6 logical ADL adapters                    
[04:12:57] ADL index 0, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:57] GPU 0 assigned: iAdapterIndex:0 iPresent:1 strUDID:PCI_VEN_1002&DEV_67B0&SUBSYS_046C1043&REV_00_4&30C250C0&0&0000A iBusNumber:101 iDeviceNumber:0 iFunctionNumber:0 iVendorID:1002 name:AMD Radeon R9 200 Series                    
[04:12:57] ADL index 1, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:57] ADL index 2, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:57] ADL index 3, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:57] ADL index 4, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:57] ADL index 5, id 877961856 - BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:57] GPU 0 AMD Radeon R9 200 Series hardware monitoring enabled                    
[04:12:57] ADL GPU 0 is Adapter index 0 and maps to adapter id 877961856                    
[04:12:57] GPU 0 BIOS partno.: 113-AD62900-101, version: 015.041.000.002, date: 2013/12/06 05:12                    
[04:12:57] Failed to ADL_Overdrive5_ODPerformanceLevels_Get                    
[04:12:57] 1 GPU devices max detected                    
[04:12:57] Specified platform that does not exist                    
[04:12:57] clDevicesNum returned error, no GPUs usable                    
[04:12:57] 0 GPU devices max detected                    
[04:12:57] Specified platform that does not exist                    
[04:12:57] clDevicesNum returned error, no GPUs usable                    
[04:12:57] 0 GPU devices max detected

**Comment by DillonN** [comment]
It looks like ADL isn't returning correct values, have you tried using different/newer drivers?

**Comment by anovickis** [comment]
I checked the ADL SDK documentation, but it's fairly sparse,  The amd developer forum with some discussion on this but not much resolution.

I went back to the _original_ drivers as shipped with the board
(It's ASUS branded R9 290 - 4GB) and it's up and running

Using the AMD latest I'm back to the problem again (Even though the AMD drivers appear to work for game purposes)

This can be closed, it's not a NiceHashMinerLegacy bug, it's something in sminer's call to the AMD dll, or in  AMD's dll
I entered this as a bug since I saw some discussion on the coin boards regarding this same symptom.
