### ISSUE TITLE
sgminer

### ISSUE THREAD

**Issue by momodigital** [nicehash/NiceHashMiner#265]
Since last night suddenly i cant run sgminer for cryptonight. the command window sudenly closed over and over. i updated to the latest nhminerlegfacy but still had the same problem. please help me, thanks

Log File :

[2017-09-03 20:30:27] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] Starting miner [pid(5444)|bin(bin\sgminer-gm\sgminer.exe)]  --gpu-platform 0 -k cryptonight --url=stratum+tcp://cryptonight.hk.nicehash.com:3355 --userpass=3P1gqGTew9UWvzoAzN5iGFzjuaAsPGfXL6.Delawa -p x  --api-listen --api-port=4000  --keccak-unroll 0 --hamsi-expand-big 4 --rawintensity 512,512,512,512,512 --worksize 4,4,4,4,4 --gpu-threads 2,2,2,2,2 --remove-disabled --device  0,1,2,3,4
[2017-09-03 20:30:27] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(5444)|bin(bin\sgminer-gm\sgminer.exe)] Starting cooldown checker
[2017-09-03 20:30:27] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(5444)|bin(bin\sgminer-gm\sgminer.exe)] Miner_Exited Will restart in 5000 ms
[2017-09-03 20:30:28] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(5444)|bin(bin\sgminer-gm\sgminer.exe)] GetAPIData reason: No connection could be made because the target machine actively refused it 127.0.0.1:4000
[2017-09-03 20:30:28] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] GetSummary returned null..
[2017-09-03 20:30:32] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(5444)|bin(bin\sgminer-gm\sgminer.exe)] Restarting miner..
[2017-09-03 20:30:32] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(5444)|bin(bin\sgminer-gm\sgminer.exe)] Shutting down miner
[2017-09-03 20:30:32] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] Trying to kill all miner processes for this instance:
[2017-09-03 20:30:32] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] Nothing to kill [pid(5444)|bin(bin\sgminer-gm\sgminer.exe)], exMsg Process with an Id of 5444 is not running.
[2017-09-03 20:30:32] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(5444)|bin(bin\sgminer-gm\sgminer.exe)] GetAPIData reason: No connection could be made because the target machine actively refused it 127.0.0.1:4000
[2017-09-03 20:30:32] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] GetSummary returned null..
[2017-09-03 20:30:32] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] Starting miner [pid(1636)|bin(bin\sgminer-gm\sgminer.exe)]  --gpu-platform 0 -k cryptonight --url=stratum+tcp://cryptonight.hk.nicehash.com:3355 --userpass=3P1gqGTew9UWvzoAzN5iGFzjuaAsPGfXL6.Delawa -p x  --api-listen --api-port=4000  --keccak-unroll 0 --hamsi-expand-big 4 --rawintensity 512,512,512,512,512 --worksize 4,4,4,4,4 --gpu-threads 2,2,2,2,2 --remove-disabled --device  0,1,2,3,4
[2017-09-03 20:30:32] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(1636)|bin(bin\sgminer-gm\sgminer.exe)] Starting cooldown checker
[2017-09-03 20:30:32] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(1636)|bin(bin\sgminer-gm\sgminer.exe)] Miner_Exited Will restart in 5000 ms
[2017-09-03 20:30:37] [INFO] [CPUDIAG] System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter.Initialize()
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NiceHashMiner.Devices.CPUComputeDevice.get_Load() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDevice\CPUComputeDevice.cs:line 18
[2017-09-03 20:30:37] [INFO] [SOCKET] Sending data: {"method":"devices.status","devices":[[0,"AMD FX(tm)-6100 Six-Core Processor",2,0,0,0],[1,"Radeon (TM) RX 470 Graphics",7,0,35,353],[2,"Radeon RX 550 Series",7,0,25,440],[3,"Radeon (TM) RX 470 Graphics",7,0,35,311],[4,"Radeon RX 550 Series",7,0,26,660],[5,"Radeon (TM) RX 470 Graphics",7,0,31,1198]]}
[2017-09-03 20:30:37] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(1636)|bin(bin\sgminer-gm\sgminer.exe)] GetAPIData reason: No connection could be made because the target machine actively refused it 127.0.0.1:4000
[2017-09-03 20:30:37] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] GetSummary returned null..
[2017-09-03 20:30:37] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(1636)|bin(bin\sgminer-gm\sgminer.exe)] Restarting miner..
[2017-09-03 20:30:37] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(1636)|bin(bin\sgminer-gm\sgminer.exe)] Shutting down miner
[2017-09-03 20:30:37] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] Trying to kill all miner processes for this instance:
[2017-09-03 20:30:37] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] Nothing to kill [pid(1636)|bin(bin\sgminer-gm\sgminer.exe)], exMsg Process with an Id of 1636 is not running.
[2017-09-03 20:30:38] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] Starting miner [pid(5956)|bin(bin\sgminer-gm\sgminer.exe)]  --gpu-platform 0 -k cryptonight --url=stratum+tcp://cryptonight.hk.nicehash.com:3355 --userpass=3P1gqGTew9UWvzoAzN5iGFzjuaAsPGfXL6.Delawa -p x  --api-listen --api-port=4000  --keccak-unroll 0 --hamsi-expand-big 4 --rawintensity 512,512,512,512,512 --worksize 4,4,4,4,4 --gpu-threads 2,2,2,2,2 --remove-disabled --device  0,1,2,3,4
[2017-09-03 20:30:38] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(5956)|bin(bin\sgminer-gm\sgminer.exe)] Starting cooldown checker
[2017-09-03 20:30:38] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(5956)|bin(bin\sgminer-gm\sgminer.exe)] Miner_Exited Will restart in 5000 ms
[2017-09-03 20:30:38] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] [pid(5956)|bin(bin\sgminer-gm\sgminer.exe)] Shutting down miner
[2017-09-03 20:30:38] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] Trying to kill all miner processes for this instance:
[2017-09-03 20:30:38] [INFO] [sgminer_AMD-MINER_ID(0)-DEVICE_IDs(0,1,2,3,4)] Nothing to kill [pid(5956)|bin(bin\sgminer-gm\sgminer.exe)], exMsg Process with an Id of 5956 is not running.

**Comment by DillonN** [comment]
Are you able to manually run sgminer with the same startup command?

**Comment by momodigital** [comment]
Yes, i have check to run manual from the folder inside bin and its running normal. Only if i run manual the sgminer ask for server to continue. Help me please thanks

**Comment by momodigital** [comment]
i just fixed my self. i go to registry using the registry finder and delete all content word sgminer-gm than i can run the nicehashminerlegacy cryptonight again niw. thankks

**Comment by momodigital** [comment]
error again, still the same case... please help

**Comment by DillonN** [comment]
Should be fixed
