### ISSUE TITLE
Internal crash leads to no connection

### ISSUE THREAD

**Issue by lorenzo93** [nicehash/NiceHashMiner#2932]
Hi,

I've just downloaded NiceHash Miner from the latest release and I'm trying to run it on a server with just CPUs. It does not have any GPU.
The client gets stuck on "connecting", but I've tried analyzing the network traffic and I couldn't find any request being made.

I've opened the logs and there is this snippet at the end of each run, I think that something crashes and it doesn't start the connection.

```
[2024-01-07 00:31:11] [ERROR] [ApplicationStateManager.Init] Exception: Object reference not set to an instance of an object. 
 TRACE:   at NHM.DeviceDetection.AMD.AMDDetector.AMDDeviceWithUniqueBUS_IDs(List`1 availableVideoControllers, OpenCLDeviceDetectionResult result)
   at NHM.DeviceDetection.AMD.AMDDetector.TryQueryAMDDevicesAsync(List`1 availableVideoControllers)
   at NHM.DeviceDetection.DeviceDetection.DetectAMDDevices()
   at NHM.DeviceDetection.DeviceDetection.DetectDevices(IProgress`1 progress)
   at NHMCore.ApplicationStateManager.InitializeManagersAndMiners(IStartupLoader loader)
```

I'm on a Windows 10 PC.
If you need any other information please, do not hesitate to ask. :)

**Comment by alanH1998** [comment]
Hi, i will take a look... are you using xmrig for CPU mining?

**Comment by lorenzo93** [comment]
Hi @alanH1998 ,

I didn't even reach the choice. Even the plugins are not downloaded.
