### ISSUE TITLE
NHMWS not connected error

### ISSUE THREAD

**Issue by anthonygamer9000** [nicehash/NiceHashMiner#2952]
Hello, I've been encountering this error and I've done everything the website said to do I flushed dns and everything i can possibly do and its still giving me the NHMWS not connected error

Here's the logs:

[2024-05-25 11:20:21] [INFO] [NICEHASH] Starting up NiceHash Miner v3.1.1.1
[2024-05-25 11:20:21] [INFO] [Translations] Found language: code: en, name: English
[2024-05-25 11:20:21] [INFO] [Translations] Found language: code: ru, name: ???????
[2024-05-25 11:20:21] [INFO] [Translations] Found language: code: de, name: Deutsch
[2024-05-25 11:20:21] [INFO] [Translations] Found language: code: fr, name: Français
[2024-05-25 11:20:21] [INFO] [Translations] Found language: code: es, name: Español
[2024-05-25 11:20:21] [INFO] [Translations] Found language: code: pt, name: Português
[2024-05-25 11:20:21] [INFO] [Translations] Found language: code: jp, name: ???
[2024-05-25 11:20:21] [INFO] [Translations] Found language: code: zh_cn, name: ????
[2024-05-25 11:20:21] [INFO] [Translations] Found language: code: si, name: Slovenski
[2024-05-25 11:20:21] [INFO] [SystemSpecs] WMI service seems to be running, ManagementObjectSearcher returned success.
[2024-05-25 11:20:21] [INFO] [NHM] Get OS version START
[2024-05-25 11:20:21] [INFO] [NHM] Get OS version END
[2024-05-25 11:20:24] [WARN] [EventManager] Could not find file 'C:\Users\antho\AppData\Local\Programs\NiceHash Miner\logs\events.json'.
[2024-05-25 11:20:24] [INFO] [SystemSpecs] FreePhysicalMemory = 4358936, 4256 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] FreeSpaceInPagingFiles = 13947568, 13620 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] FreeVirtualMemory = 8578804, 8377 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] LargeSystemCache = 0, 0 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] MaxNumberOfProcesses = 4294967295, 4194303 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] MaxProcessMemorySize = 137438953344, 134217727 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] NumberOfLicensedUsers = 0, 0 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] NumberOfProcesses = 236, 0 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] NumberOfUsers = 2, 0 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] OperatingSystemSKU = 48, 0 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] SizeStoredInPagingFiles = 14680064, 14336 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] SuiteMask = 272, 0 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] TotalSwapSpaceSize = 0, 0 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] TotalVirtualMemorySize = 31421824, 30685 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] TotalVisibleMemorySize = 16741760, 16349 MB
[2024-05-25 11:20:24] [INFO] [SystemSpecs] PageFileSize = 14680064, 14336 MB
[2024-05-25 11:20:24] [INFO] [DeviceDetection] DetectCPU START
[2024-05-25 11:20:24] [INFO] [CPUDetector] TryQueryCUDADevicesAsync START cpu -n
[2024-05-25 11:20:24] [INFO] [CPUDetector] TryQueryCUDADevicesAsync END cpu -n
[2024-05-25 11:20:24] [INFO] [CPUDetector] {"AMD":false,"Intel":true,"IsZen":false,"L3KB_size":20480,"Name":"       Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz","PhysicalProcessorCount":2,"SupportsAES_SSE42":true,"SupportsAVX":true,"SupportsAVX2":false,"SupportsSSE2":true,"Vendor":"GenuineIntel"}
[2024-05-25 11:20:26] [INFO] [DeviceDetection] Found CPU:
        UUID: CPU-9fc61496-4f11-5561-a72e-2e64540e4a6d
        Name: (2x)Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
        PhysicalProcessorCount: 2
        ThreadsPerCPU: 16
        SupportsHyperThreading: True

[2024-05-25 11:20:26] [INFO] [DeviceDetection] DetectCPU END
[2024-05-25 11:20:26] [INFO] [VideoControllerDetector] QueryWin32_VideoControllerTask START
[2024-05-25 11:20:26] [INFO] [DeviceBusDetector] QueryWin32_DeviceBusPCITask START
[2024-05-25 11:20:26] [INFO] [DeviceDetection] NVIDIA driver version: N/A
AMD driver version: N/A
QueryVideoControllers:
        Win32_VideoController detected:
                Name: Microsoft Basic Display Adapter
                Description: Microsoft Basic Display Adapter
                PNPDeviceID: PCI\VEN_102B&DEV_0533&SUBSYS_3381103C&REV_00\4&15D41075&0&01E7
                DriverVersion: 10.0.19041.3636
                Status: OK
                InfSection: MSBDA
                AdapterRAM: 0
                PCI_BUS_ID: 1

[2024-05-25 11:20:26] [INFO] [CUDADetector] TryQueryCUDADevicesAsync START cuda -n
[2024-05-25 11:20:26] [INFO] [CUDADetector] TryQueryCUDADevicesAsync END cuda -n
[2024-05-25 11:20:26] [INFO] [DeviceDetection] TryQueryCUDADevicesAsync RAW: '{"CudaDevices":[],"DriverVersion":"","ErrorString":"CUDA driver version is insufficient for CUDA runtime version","NvmlInitialized":0,"NvmlLoaded":0}'
[2024-05-25 11:20:26] [INFO] [DeviceDetection]
DetectCUDADevices:
        NOT SUPPORTED/SKIPPED DEVICES ZERO
        SUPPORTED/ADDED DEVICES ZERO

[2024-05-25 11:20:26] [INFO] [AMDDetector] TryQueryAMDDevicesAsync START
[2024-05-25 11:20:26] [INFO] [OpenCLDetector] TryQueryOpenCLDevicesAsync START
[2024-05-25 11:20:26] [ERROR] [DeviceDetectionPrinter] threw Exception: 'Unexpected character encountered while parsing value: C. Path '', line 0, position 0.'. ReadData 'Cannot load 'device_detection_opencl_adl.dll''
[2024-05-25 11:20:26] [INFO] [OpenCLDetector] TryQueryOpenCLDevicesAsync END
[2024-05-25 11:20:26] [INFO] [AMDDetector] TryQueryOpenCLDevicesAsync RAW: 'Cannot load 'device_detection_opencl_adl.dll''
[2024-05-25 11:20:26] [ERROR] [ApplicationStateManager.Init] Exception: Object reference not set to an instance of an object.
 TRACE:   at NHM.DeviceDetection.AMD.AMDDetector.AMDDeviceWithUniqueBUS_IDs(List`1 availableVideoControllers, OpenCLDeviceDetectionResult result)
   at NHM.DeviceDetection.AMD.AMDDetector.TryQueryAMDDevicesAsync(List`1 availableVideoControllers, Boolean detectIntegrated)
   at NHM.DeviceDetection.DeviceDetection.DetectAMDDevices(Boolean detectIntegrated)
   at NHM.DeviceDetection.DeviceDetection.DetectDevices(Boolean detectIntegrated, IProgress`1 progress)
   at NHMCore.ApplicationStateManager.InitializeManagersAndMiners(IStartupLoader loader)

If someone could please help me with this that would be great.

![image](https://github.com/nicehash/NiceHashMiner/assets/145726498/4fb888bc-9457-4a8f-bc06-ea88086a0d64)

**Comment by alanH1998** [comment]
hi, please check if there is a file `device_detection_opencl_adl.dll` inside `nhm_directory\app_3.1.x.x`. Lately windows has been very aggressive with cleaning our dlls
