### ISSUE TITLE
NHML-1.8.1.5-  crush - unhandled exception at start

### ISSUE THREAD

**Issue by Michael7775** [nicehash/NiceHashMiner#714]
At start give this and all is blocked. 
This happens in all versions. ..Users\Dillon\.. is not my user.
My conf: rx 460, cpu xeon e5450, 4gb ram

This is details text:

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x800706BE)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at NiceHashMiner.CPUID.GetNumberOfCores() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\PInvoke\CPUID.cs:line 59
   at NiceHashMiner.Devices.ComputeDeviceManager.Query.CPU.QueryCPUs() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDeviceManager.cs:line 394
   at NiceHashMiner.Devices.ComputeDeviceManager.Query.QueryDevices(IMessageNotifier messageNotifier) in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDeviceManager.cs:line 178
   at NiceHashMiner.Form_Main.StartupTimer_Tick(Object sender, EventArgs e) in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Forms\Form_Main.cs:line 265
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![crush](https://user-images.githubusercontent.com/34212201/33526142-16ff5722-d845-11e7-8eda-2e87ed008401.jpg)

**Comment by DillonN** [comment]
Looks like an issue with WMI. You can try to debug it:

Win+R -> enter wbemtest -> open

Click connect at the top right, then connect on the new window with default settings

Click Query in the main screen, then enter the query string "Select * from Win32_Processor"

If you get a more meaningful error than remote procedure call failed, you can try to get more info about that error. If you get RPC failed, likely the OS is corrupt. If there's no error and you get a response then something is wrong with NHML

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
