### ISSUE TITLE
AMD GPU detected but not added

### ISSUE THREAD

**Issue by Heartsbane** [nicehash/NiceHashMiner#754]
Running NiceHash Miner 1.8.1.5 on Windows 10 (x64). My AMD GPU is detected (according to the log) but is not showing up in the list of devices. Here is a snippet from the log:

[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] QueryOpenCLDevices START
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] 
AMDOpenCLDeviceDetection found devices success:
	Found devices for platform: AMD Accelerated Parallel Processing
		Device:
			Device ID 0
			Device NAME Pitcairn
			Device TYPE GPU

[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] QueryOpenCLDevices END
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] QueryAMD START
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): AMD Radeon (TM) R9 200 Series (23.20.15002.11)
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] Driver version seems to be 21.19.164.1 or higher. NeoScrypt and Lyra2REv2 will be removed from list
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] AMD platform found: Key: AMD Accelerated Parallel Processing, Num: 0
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] AMD Bus IDs are unique and valid. OK
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] AMD GPUs count : 1
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] AMD Getting device name and serial from ADL
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] Number Of Adapters: 16
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] Using AMD device creation DEFAULT Reliable mappings
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] AMD OpenCL and ADL AMD query COUNTS GOOD/SAME
[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] 
QueryAMD [DEFAULT query] devices: 
	Device not added, Bus No. 0 not found:

[2017-12-21 21:34:05] [INFO] [ComputeDeviceManager.Query] QueryAMD END
[2017-12-21 21:34:06] [INFO] [ComputeDeviceManager.Query] Cuda NVIDIA/CUDA device count GOOD
[2017-12-21 21:34:06] [INFO] [ComputeDeviceManager.Query] AMD GPU device count GOOD
[2017-12-21 21:34:06] [INFO] [ComputeDeviceManager.Query] virtual memory size GOOD

...but the GPU is not showing up in the device list:

![nicehash](https://user-images.githubusercontent.com/7918993/34283072-bda3af3c-e697-11e7-8fb8-28de19a001d9.PNG)

Any ideas? I've run NiceHash Miner on several other PCs and have never had a problem like this before.

**Comment by Heartsbane** [comment]
This seems to be a duplicate of Issue #740 - I will revert back to pre-Adrenaline AMD driver to verify.

Thanks!

**Comment by SK1NN3RSA** [comment]
reverting to previous drivers of amd eg 17.11.2 it works however i found the older legacy miner does work now i am using 1.7.5.9 and my gpu's is detecting and working

**Comment by Jakobhoss** [comment]
Simply make a .bat file with exact this text
Only change the information about the NiceHash folder and put it into your autostart folder!

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_SINGLE_ALLOC_PERCENT 100
setx GPU_MAX_ALLOC_PERCENT 100
<Your NH LEGACY FOLDER\bin_3rdparty\claymore_cryptonight\NsGPUCNMINER -xpool stratum+ssl://etn-eu2.nanopool.org:13433 -xwal etnjx5yvXLheSRw7Ed5yqbh3RxrPQAbvsimVoUEkzizoNEajuVBTbCdTDxgWE8vdkV9gEi78gFweWJJXjvUjuurf646whtvunT.Yomabitch -xpsw x -allpools 1 -nofee 1

Works 100% you´ll have to wait for some hours till you see first results but it´s worth it!

**Comment by SaintPistachio** [comment]
Do not forgot to change the wallet address otherwise you will just mine for someone else. ;)

**Comment by 3ncoded** [comment]
Sorta the same thing here, [2017-12-25 11:52:27] [INFO] [NICEHASH] Starting up NiceHashMiner v1.8.2.0
[2017-12-25 11:52:27] [INFO] [NICEHASH] Selected language: English
[2017-12-25 11:52:27] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.
[2017-12-25 11:52:27] [INFO] [SystemSpecs] FreePhysicalMemory = 6582224
[2017-12-25 11:52:27] [INFO] [SystemSpecs] FreeSpaceInPagingFiles = 4194304
[2017-12-25 11:52:27] [INFO] [SystemSpecs] FreeVirtualMemory = 10741888
[2017-12-25 11:52:27] [INFO] [SystemSpecs] LargeSystemCache = 0
[2017-12-25 11:52:27] [INFO] [SystemSpecs] MaxNumberOfProcesses = 4294967295
[2017-12-25 11:52:27] [INFO] [SystemSpecs] MaxProcessMemorySize = 137438953344
[2017-12-25 11:52:27] [INFO] [SystemSpecs] NumberOfLicensedUsers = 0
[2017-12-25 11:52:27] [INFO] [SystemSpecs] NumberOfProcesses = 105
[2017-12-25 11:52:27] [INFO] [SystemSpecs] NumberOfUsers = 2
[2017-12-25 11:52:27] [INFO] [SystemSpecs] OperatingSystemSKU = 121
[2017-12-25 11:52:27] [INFO] [SystemSpecs] SizeStoredInPagingFiles = 4194304
[2017-12-25 11:52:27] [INFO] [SystemSpecs] SuiteMask = 272
[2017-12-25 11:52:27] [INFO] [SystemSpecs] TotalSwapSpaceSize = 0
[2017-12-25 11:52:27] [INFO] [SystemSpecs] TotalVirtualMemorySize = 12534592
[2017-12-25 11:52:27] [INFO] [SystemSpecs] TotalVisibleMemorySize = 8340288
[2017-12-25 11:52:27] [INFO] [NICEHASH] Total RAM: 8144MB
[2017-12-25 11:52:27] [INFO] [NICEHASH] Page File Size: 4096MB
[2017-12-25 11:52:27] [INFO] [NICEHASH] Balance update
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ccminer
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ccminer_CryptoNight
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ethminer_OCL
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ethminer_CUDA
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_sgminer
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_cpuminer_opt
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_nheqminer_CPU
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_nheqminer_CUDA
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_eqm_CUDA
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreZcash
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreCryptoNight
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_OptiminerZcash
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_excavator
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreDual
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_EWBF
[2017-12-25 11:52:28] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_Xmrig
[2017-12-25 11:52:28] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_AMD_OpenCL
[2017-12-25 11:52:28] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_NVIDIA_2_1
[2017-12-25 11:52:28] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_NVIDIA_3_x
[2017-12-25 11:52:28] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_NVIDIA_5_x
[2017-12-25 11:52:28] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_NVIDIA_6_x
[2017-12-25 11:52:28] [INFO] [ComputeDeviceManager.Query] 
QueryVideoControllers: 
	Win32_VideoController detected:
		Name AMD Radeon HD 6900 Series
		Description AMD Radeon HD 6900 Series
		PNPDeviceID PCI\VEN_1002&DEV_6719&SUBSYS_0B001002&REV_00\4&1C3D25BB&0&0019
		DriverVersion 15.301.1901.0
		Status OK
		InfSection ati2mtag_NICayman
		AdapterRAM 2147483648

[2017-12-25 11:52:28] [INFO] [ComputeDeviceManager.Query] QueryCPUs START
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] HyperThreadingEnabled = FALSE
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] QueryCPUs END
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] Skipping NVIDIA device detection, settings are set to disabled
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] QueryOpenCLDevices START
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] 
AMDOpenCLDeviceDetection found devices success:
	Found devices for platform: AMD Accelerated Parallel Processing

[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] QueryOpenCLDevices END
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] QueryAMD START
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] Checking AMD device (driver): AMD Radeon HD 6900 Series (15.301.1901.0)
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] AMD platform found: Key: AMD Accelerated Parallel Processing, Num: 0
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] AMD GPUs count is 0
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] QueryAMD END
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] Cuda NVIDIA/CUDA device count GOOD
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] AMD GPU device count BAD!!!
[2017-12-25 11:52:29] [INFO] [ComputeDeviceManager.Query] virtual memory size GOOD
[2017-12-25 11:52:29] [INFO] [SOCKET] 12/25/2017 11:52:29|Warn |Logger.set_Output|The current output action has been changed.
[2017-12-25 11:52:29] [INFO] [SOCKET] 12/25/2017 11:52:29|Debug|WebSocket.sendHttpRequest|A request to the server:
                          GET /v2/nhm HTTP/1.1
                          User-Agent: websocket-sharp/1.0
                          Host: api.nicehash.com
                          Upgrade: websocket
                          Connection: Upgrade
                          Sec-WebSocket-Key: OxKiLsYHXNps92AcLpKDyQ==
                          Sec-WebSocket-Version: 13
[2017-12-25 11:52:29] [INFO] [SOCKET] 12/25/2017 11:52:29|Debug|WebSocket.sendHttpRequest|A response to this request:
                          HTTP/1.1 101 Switching Protocols
                          Date: Mon, 25 Dec 2017 10:52:03 GMT
                          Connection: upgrade
                          Set-Cookie: __cfduid=dd5db34dfc8d0a6d6d54c5388de6086cf1514199123; expires=Tue, 25-Dec-18 10:52:03 GMT; path=/; domain=.nicehash.com; HttpOnly
                          Sec-WebSocket-Accept: kUh+DSZqAU6mvRolWEHfBQnhsAc=
                          Upgrade: WebSocket
                          Server: cloudflare-nginx
                          CF-RAY: 3d2b3fac28109d44-AMS
[2017-12-25 11:52:29] [INFO] [SOCKET] Sending data: {"method":"login","version":"NHML/1.8.2.0","protocol":1}
[2017-12-25 11:52:30] [INFO] [CPUDIAG] System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter.Initialize()
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NiceHashMiner.Devices.CPUComputeDevice.get_Load() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDevice\CPUComputeDevice.cs:line 18
[2017-12-25 11:52:30] [INFO] [SOCKET] Sending data: {"method":"devices.status","devices":[[0,"AMD Ryzen 3 1200 Quad-Core Processor",2,0,0,0]]}
[2017-12-25 11:52:30] [INFO] [SOCKET] Received: {"method":"versions","v2":"2.0.1.1","legacy":"1.8.1.2"}
[2017-12-25 11:52:30] [INFO] [SOCKET] Received: {"method":"sma","data":[[5,"0.00024485"],[7,"0.00578304"],[8,"0.26885635"],[14,"0.00809211"],[20,"0.00670595"],[21,"0.0000582"],[22,"296.52687001"],[23,"0.00098803"],[24,"598.34508792"],[25,"0.0001263"],[26,"0.0197647"],[27,"0.0001215"],[28,"0.00006701"],[29,"0.00765256"]]}
[2017-12-25 11:52:30] [INFO] [NICEHASH] SMA Update
[2017-12-25 11:52:30] [INFO] [SOCKET] Received: {"method":"exchange_rates","data":"{\"exchanges\":[{\"USD\":\"14013\",\"coin\":\"BTC\"},{\"BTC\":\"0\",\"coin\":\"LTC\"},{\"BTC\":\"0\",\"coin\":\"ETH\"},{\"BTC\":\"0\",\"coin\":\"ZEC\"},{\"BTC\":\"0\",\"coin\":\"XMR\"}],\"exchanges_fiat\":{\"CHF\":0.99004,\"HRK\":6.3629,\"MXN\":19.511,\"ZAR\":12.705,\"INR\":64.039,\"CNY\":6.576,\"THB\":32.76,\"AUD\":1.2957,\"ILS\":3.4848,\"KRW\":1076.8,\"JPY\":113.36,\"PLN\":3.5413,\"GBP\":0.74722,\"IDR\":13558.0,\"HUF\":263.07,\"PHP\":50.099,\"TRY\":3.8176,\"RUB\":58.293,\"HKD\":7.8164,\"EUR\":0.84367,\"DKK\":6.2805,\"CAD\":1.2703,\"MYR\":4.0795,\"BGN\":1.65,\"NOK\":8.3492,\"RON\":3.9163,\"SGD\":1.3439,\"CZK\":21.724,\"SEK\":8.3799,\"NZD\":1.4261,\"BRL\":3.3198}}"}
[2017-12-25 11:52:30] [INFO] [SOCKET] Sending data: {"method":"credentials.set","btc":"3PRbcTdxbRcToozqEbi9vYfaPzRxGE2vPD","worker":"worker1"}
[2017-12-25 11:52:30] [INFO] [SOCKET] Received: {"method":"balance","value":"0.00000136"}
[2017-12-25 11:52:30] [INFO] [NICEHASH] Balance update
[2017-12-25 11:52:30] [INFO] [NICEHASH] Bitcoin rate get
[2017-12-25 11:52:30] [INFO] [NICEHASH] Current Bitcoin rate: 14013.00
[2017-12-25 11:52:30] [INFO] [NICEHASH] Setting environment variables
[2017-12-25 11:52:30] [INFO] [NICEHASH] Trying to enable/disable Windows error reporting
[2017-12-25 11:52:30] [INFO] [NICEHASH] Current DontShowUI value: 1


and the gpu doesn't show up, suggestions?

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
