### ISSUE TITLE
GPULost false positive

### ISSUE THREAD

**Issue by moonoiza** [nicehash/NiceHashMiner#786]
I've found that OnGPULost.bat has been executed several times.
I though that there might have been something wrong with OC settings until I decided to put NirCMD to capture screenshot and I saw that everything was OK.
There is something wrong in log.txt, It could have been a CPU check but I'm pretty sure that CPU mining has been disabled.

**[2017-12-30 09:20:14] [INFO] [CPUDIAG] System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.**
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter.Initialize()
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NiceHashMiner.Devices.CPUComputeDevice.get_Load() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\Devices\ComputeDevice\CPUComputeDevice.cs:line 18
**[2017-12-30 09:20:15] [INFO] [ComputeDeviceManager.CheckCount] CUDA GPUs count: Old: 8 / New: 0**

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
