### ISSUE TITLE
Legacy miner v1.8.1.8 - Socket connection unsuccessfull - System.InvalidOperationException

### ISSUE THREAD

**Issue by mves001** [nicehash/NiceHashMiner#990]
Legacy miner v1.8.1.8 have some kind of bug that often pop up and only restarting miner helps.

[09:33:29] [SOCKET] System.InvalidOperationException: A series of reconnecting has failed.
   at WebSocketSharp.WebSocket.Connect()
   at NiceHashMiner.NiceHashStats.NiceHashConnection.AttemptReconnect() in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\NiceHashStats.cs:line 269
   at NiceHashMiner.NiceHashStats.NiceHashConnection.SendData(String data, Boolean recurs) in C:\Users\Dillon\Documents\Code\NiceHashMiner\NiceHashMiner\NiceHashStats.cs:line 210
[09:34:09] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
[09:35:09] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
[09:36:09] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
[09:37:09] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)

**Comment by harelzar** [comment]
have the same problem, it start few days ago

**Comment by buljaka** [comment]
same here-...

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

Temporary back-end service issue not related to miner client.
